spring:
  application:
    name: myidcustomapi-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=userdb;encrypt=true;trustServerCertificate=true
    username: sa
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

#server:
#  servlet:
#    context-path: /myidcustomapi

  ldap:
    search-subtree: true
    base: "DC=mycomp,DC=com"
    urls: "ldap://WIN-MMN2C3CV8L4:389"
    username: "administrator@mycomp.com"
    password: "@Simhalp9"
    base-environment:
      java.naming.referral: ignore
      java.naming.ldap.attributes.binary: objectGUID
  main:
    allow-bean-definition-overriding: true


logging:
  config: classpath:logback-spring.xml
#  level:
#    org.springframework.security: DEBUG

ldap:
  user:
    base-filter: "(objectCategory=person)"
    default-attributes:
      - distinguishedName
      - cn
      - mail
      - sAMAccountName
      - givenName
      - sn
      - name
      - userPrincipalName
  group:
    base-filter: "(objectClass=group)"
    default-attributes:
      - distinguishedName
      - groupCategory
      - groupScope
      - cn
      - name
      - sAMAccountName
      - description
      - member
      - objectGUID
  computer:
    base-filter: "(objectClass=computer)"
    default-attributes:
      - distinguishedName
      - groupCategory
      - groupScope
      - cn
      - name
      - sAMAccountName
      - description
      - member
      - objectGUID